export const PROJECT_ADD_REQUEST = "PROJECT_ADD_REQUEST";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";
export const PROJECT_ADD_RESET = "PROJECT_ADD_RESET";

export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";
export const PROJECT_DETAILS_RESET = "PROJECT_DETAILS_RESET";

export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";
export const PROJECT_DELETE_RESET = "PROJECT_DELETE_RESET";

export const PROJECT_UPDATE_REQUEST = "PROJECT_UPDATE_REQUEST";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
export const PROJECT_UPDATE_RESET = "PROJECT_UPDATE_RESET";

export const LIKED_PROJECT_REQUEST = "LIKED_PROJECT_REQUEST";
export const LIKED_PROJECT_SUCCESS = "LIKED_PROJECT_SUCCESS";
export const LIKED_PROJECT_FAIL = "LIKED_PROJECT_FAIL";

export const VIEWED_PROJECT_REQUEST = "VIEWED_PROJECT_REQUEST";
export const VIEWED_PROJECT_SUCCESS = "VIEWED_PROJECT_SUCCESS";
export const VIEWED_PROJECT_FAIL = "VIEWED_PROJECT_FAIL";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAIL = "SEARCH_PROJECT_FAIL";
