export const technologies = [
  "HTML",
  "CSS",
  "Javascript",
  "React.js",
  "Angular.js",
  "Vue.js",
  "Express.js",
  "Node.js",
  "Next.js",
  "Nest.js",
  "Bootstrap",
  "Material UI",
  "Mongo DB",
  "Ansible",
  "Android",
  ".NET CORE",
  "Alpine.js",
  "Apache Hadoop",
  "Apex",
  "AWS",
  "ASP.NET",
  "Bulma",
  "BackboneJS",
  "C",
  "C++",
  "C#",
  "Java",
  "Python",
  "Cassandra",
  "Django",
  "Docker",
  "CodeIgniter",
  "Cycle.js",
  "Electron",
  "Ember.js",
  "Elixir",
  "Flask",
  "Firebase",
  "Ember",
  "DynamoDB",
  "Flutter",
  "Gatsby Js",
  "GIT",
  "Github",
  "Golang",
  "GraphQL",
  "Hibernate",
  "ionic",
  "Jenkins",
  "jQuery",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Machine Learning",
  "MariaDB",
  "Material",
  "Materialize",
  "MySQL",
  "Perl",
  "PHP",
  "PostgreSQL",
  "R",
  "React Native",
  "Redux",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "Salesforce Developer",
  "Scala",
  "SQL",
  "Spring",
  "Svelte",
  "Swift",
  "Tailwind CSS",
  "Typescript",
  "Unity",
  "Unreal",
  "Web3",
  "Zustand",
];

export const keywords = [
  "E-Commerce",
  "Social Media",
  "Job Search",
  "Resume Builder",
  "CRUD Application",
  "Trading",
  "Healthcare",
  "Gaming",
  "Authentication",
  "Checkout",
  "Landing Page",
  "Calculator",
  "Music Player",
  "Direct Messaging",
  "Analytics Chart",
  "Location Tracker",
  "Search",
  "TV App",
  "Crowdfunding",
  "Blogging",
  "Weather",
  "Calendar",
  "Recipe",
  "Workout Tracker",
  "ToDo List",
  "Video Player",
  "Color Picker",
  "Hotel Booking",
  "Flight Search",
  "Event Listing",
  "Download App",
  "Currency Converter",
  "Email Application",
  "Portfolio",
  "E-Wallet",
  "Project Management",
  "Code Editor",
  "Travel Destination",
  "Real Estate",
];
